language: node_js
node_js:
  - '8'

# base machine image for VM
dist: trusty
# trusty is a very specific version of linux customised to run small tasks - tests ext

# services are aspects required to run the program correctly: DB Redis etc
# when the VM starts up these services will also start
# for testing purposes these services would be mocked and not necessary in the ci
services:
  - mongodb
  - redis-server

# set environment variables
# if using jest use "setupFiles": ["<rootDir>/jest/set-env.ts"] to use .env.test config
# this should prevent the need to set node_env below
env:
  - NODE_ENV=ci PORT=3000

# Caching the Node_Modules folder will speed up the build time during the CI
# when npm i is run and there are no changes then the build saves time.
cache:
  directories:
    - node_modules
    - client/node_modules
# runs commands at the commandline
install:
  - npm i
  - npm run build

# allows commands to be run
# nohup (no hang up) prevents background proceses running when command line it killed
# & tells the OS to run the command in the background (sub shell)
# sleep 3 creates a 3 second delay, allows server to start up
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
