# https://docs.github.com/actions

name: CI/CD GitHub Actions Example
# hooks to control when the workflow runs. Can use on: [push] to catch all branches push and merge
on:
  # whenever code is pushed to [these branches]
  push:
    branches:
      - master
  # whenever a branch is going to merge into [these branches]
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Checks
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'postgresql://admin:example@localhost:5432/postgres?schema=public'
      NODE_VERSION: 20.x
      REDIS_VERSION: latest

    steps:
      # configures a PostgreSQL DB instance in the CI for tests. Connect via localhost or 0.0.0.0:PORT
      # https://github.com/marketplace/actions/setup-postgresql-for-linux-macos-windows
      - name: Setup DB
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: admin
          password: example
          database: postgres
          port: 5432

      - name: Start Redis
        uses: supercharge/redis-github-action@1.6.0
        with:
          redis-version: ${{ env.REDIS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Spellcheck
        id: cspell-action
        uses: streetsidesoftware/cspell-action@v2
        with:
          verbose: true
          incremental_files_only: false
          files: |
            /**
            !/__*
            !/*.{json,txt}
            !/prisma
            !/coverage
            !/node_modules

      - name: Install Dependancies
        run: npm ci

      - name: Migrate DB
        run: npm run migrate:test

      - name: Run Tests
        run: npm run test
