# https://docs.github.com/actions

name: CI/CD GitHub Actions Example
on:
  # applies to any brance EXCEPT master
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  checks:
    permissions:
      contents: write
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Spellcheck
        id: cspell-action
        uses: streetsidesoftware/cspell-action@v2
        with:
          verbose: true
          files: |
            /src/**/*.{ts,js,tsx,md}
            /readme.md

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,ts,tsx,md}

  tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    needs: checks

    env:
      DATABASE_URL: 'postgresql://admin:example@localhost:5432/postgres?schema=public'
      NODE_VERSION: 20.x
      REDIS_VERSION: latest

    steps:
      # configures a PostgreSQL DB instance in the CI for tests. Connect via localhost or 0.0.0.0:PORT
      # https://github.com/marketplace/actions/setup-postgresql-for-linux-macos-windows
      - name: Start DB
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: admin
          password: example
          database: postgres
          port: 5432

      - name: Start Redis
        uses: supercharge/redis-github-action@1.6.0
        with:
          redis-version: ${{ env.REDIS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependancies
        run: npm ci

      - name: Migrate DB
        run: npm run migrate:test

      - name: Run Tests
        run: npm run test
