# https://docs.github.com/actions

name: CI/CD Formatting with commit
on:
  push:
    branches-ignore:
      - master

permissions:
  contents: write

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20.x

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Spellcheck
        id: cspell-action
        uses: streetsidesoftware/cspell-action@v2
        with:
          verbose: true
          files: |
            /src/**/*.{ts,js,tsx,md}
            /readme.md

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,ts,tsx,md}
